import 'dart:math';

import 'package:drink_tea/db/provider/OrdersItemsAdd_provider.dart';
import 'package:drink_tea/db/provider/OrdersItems_provider.dart';
import 'package:drink_tea/db/provider/Orders_provider.dart';
import 'package:drink_tea/db/provider/Pictures_provider.dart';
import 'package:drink_tea/db/provider/TeaShowChoseText_provider.dart';
import 'package:drink_tea/db/provider/TeaShow_provider.dart';
import 'package:drink_tea/db/provider/UserAddress_provider.dart';
import 'package:drink_tea/db/provider/User_provider.dart';

import 'db_data_utill.dart';

///测试语句
void TheSQLTestText() async{
    TeaShowProvider teaShowProvider = TeaShowProvider();
    // await teaShowProvider.insert(TeaShow_add01);
    // await teaShowProvider.insert(TeaShow_add02);
    // await teaShowProvider.insert(TeaShow_add03);
    // await teaShowProvider.insert(TeaShow_add04);
    // await teaShowProvider.insert(TeaShow_add05);
    // await teaShowProvider.insert(TeaShow_add06);
    // await teaShowProvider.insert(TeaShow_add07);
    // await teaShowProvider.insert(TeaShow_add08);
    // await teaShowProvider.insert(TeaShow_add09);
    // await teaShowProvider.insert(TeaShow_add10);
    // await teaShowProvider.insert(TeaShow_add11);
    // await teaShowProvider.insert(TeaShow_add12);
    // await teaShowProvider.insert(TeaShow_add13);
    // await teaShowProvider.insert(TeaShow_add14);
    // await teaShowProvider.insert(TeaShow_add15);
    // await teaShowProvider.insert(TeaShow_add16);
    // await teaShowProvider.insert(TeaShow_add17);
    // await teaShowProvider.insert(TeaShow_add18);
    // await teaShowProvider.insert(TeaShow_add19);
    // await teaShowProvider.insert(TeaShow_add20);
    // await teaShowProvider.insert(TeaShow_add21);
    // await teaShowProvider.insert(TeaShow_add22);
    // await teaShowProvider.insert(TeaShow_add23);
    // await teaShowProvider.insert(TeaShow_add24);
    // await teaShowProvider.insert(TeaShow_add25);
    // await teaShowProvider.insert(TeaShow_add26);
    // await teaShowProvider.insert(TeaShow_add27);
    await teaShowProvider.insert(TeaShow_add28);
    await teaShowProvider.update(TeaShow_update01,"tea_id","1");
    await teaShowProvider.queryTableBySingleField("tea_id","1");
    await teaShowProvider.queryTableAll();
    await teaShowProvider.getTableCount();
    // await teaShowProvider.deleteBySingleField("tea_id","7");


    //await teaShowProvider.dropTable();
    TeaShowChoseTextProvider teaShowChoseTextProvider = TeaShowChoseTextProvider();
    await teaShowChoseTextProvider.insert(TeaShowChoseText_add01);
    await teaShowChoseTextProvider.insert(TeaShowChoseText_add02);
    await teaShowChoseTextProvider.insert(TeaShowChoseText_add03);
    await teaShowChoseTextProvider.update(TeaShowChoseText_update01,"chose_id","c003");
    await teaShowChoseTextProvider.queryTableBySingleField("chose_id","c002");
    await teaShowChoseTextProvider.queryTableAll();
    await teaShowChoseTextProvider.getTableCount();
    // await teaShowChoseTextProvider.deleteBySingleField("chose_id","c002");
    //await teaShowChoseTextProvider.dropTable();
    OrdersProvider providerUsed1 = new OrdersProvider();
    await providerUsed1.insert(Orders_add001);
    await providerUsed1.insert(Orders_add002);
    await providerUsed1.insert(Orders_add003);
    await providerUsed1.update(Orders_update003,"orders_id","o003");
    await providerUsed1.queryTableBySingleField("orders_id","o003");
    await providerUsed1.queryTableAll();
    await providerUsed1.getTableCount();
    await providerUsed1.deleteBySingleField("orders_id","o003");
    await providerUsed1.dropTable();
    OrdersItemsProvider providerUsed2 = new OrdersItemsProvider();
    await providerUsed2.insert(OrdersItems_add001);
    await providerUsed2.insert(OrdersItems_add002);
    await providerUsed2.insert(OrdersItems_add003);
    await providerUsed2.update(OrdersItems_update003,"orders_items_id","ot003");
    await providerUsed2.queryTableBySingleField("orders_items_id","ot003");
    await providerUsed2.queryTableAll();
    await providerUsed2.getTableCount();
    // await providerUsed2.deleteBySingleField("orders_items_id","ot003");
    // await providerUsed2.dropTable();
    OrdersItemsAddProvider providerUsed3 = new OrdersItemsAddProvider();
    await providerUsed3.insert(OrdersItemsAdd_add001);
    await providerUsed3.insert(OrdersItemsAdd_add002);
    await providerUsed3.insert(OrdersItemsAdd_add003);
    await providerUsed3.update(OrdersItemsAdd_update003,"orders_items_add_id","otadd003");
    await providerUsed3.queryTableBySingleField("orders_items_add_id","otadd003");
    await providerUsed3.queryTableAll();
    await providerUsed3.getTableCount();
    // await providerUsed3.deleteBySingleField("orders_items_add_id","otadd003");
    // await providerUsed3.dropTable();
    PicturesProvider providerUsed4 = new PicturesProvider();
    await providerUsed4.insert(Pictures_add001);
    await providerUsed4.insert(Pictures_add002);
    await providerUsed4.insert(Pictures_add003);
    await providerUsed4.update(Pictures_update001,"pic_id","p003");
    await providerUsed4.queryTableBySingleField("pic_id","p003");
    await providerUsed4.queryTableAll();
    await providerUsed4.getTableCount();
    // await providerUsed4.deleteBySingleField("pic_id","p003");
    // await providerUsed4.dropTable();
    UserProvider providerUsed5 = new UserProvider();
    await providerUsed5.insert(User_add001);
    await providerUsed5.insert(User_add002);
    await providerUsed5.insert(User_add003);
    await providerUsed5.update(User_update001,"user_id","user001");
    await providerUsed5.queryTableBySingleField("user_id","user001");
    await providerUsed5.queryTableAll();
    await providerUsed5.getTableCount();
    // await providerUsed5.deleteBySingleField("user_id","user001");
    // await providerUsed5.dropTable();
    UserAddressProvider providerUsed6 = new UserAddressProvider();
    await providerUsed6.insert(UserAddress_add001);
    await providerUsed6.insert(UserAddress_add002);
    await providerUsed6.insert(UserAddress_add003);
    await providerUsed6.update(UserAddress_update001,"address_id","ua001");
    await providerUsed6.queryTableBySingleField("address_id","ua001");
    await providerUsed6.queryTableAll();
    await providerUsed6.getTableCount();
    // await providerUsed6.deleteBySingleField("address_id","ua001");
    // await providerUsed6.dropTable();
}
